---
title: "Students of Professor Ardo Chimah Ezeomah"
author: "Curated by Chiomah Ezeomah, B.A (Uni at Buffalo); B.Sc (Uni at Buffalo); MSc (Cornell); MSc (Oxford)"
date: "November 26, 2025" 
output: 
  html_document:
    toc: true
    toc_float: true
    theme: flatly
    css: "styles.css"
header-includes:
  - |
    <!-- Google tag (gtag.js) -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=G-9MJGP8FYXZ"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());
      gtag('config', 'G-9MJGP8FYXZ');
    </script>
---

### Amb (Prof.) Mary Nansep Lar

**Thesis Title:** An Analytical Case-Study of Nomadic Education in Plateau State. Ph.D. Thesis presented to The Department of Curriculum Studies; Faculty of Education, University of Jos in partial fulfillment of the degree of Doctor of Philosophy. 

**Month/ Year:** September 1985. 

**Supervisors:** Professor P. N. Lassa; Dr. Chimah Ezeomah

### Honorable (Dr.) Kachallom Pyam Gang

### Prof. Godwin Owoicho Agba, Ph.D.

### Dr. James Bature

### Onwuka Obialo J. (Year 1981)

### Ephraim Afam Nwofor 

**Thesis Title:** Managing Anambra Colleges of Education in Line with P.P.B.S. Demands - An Analysis of Operational PPBS in an African Environment (Ph.D. Candidate in Educational Administration) 

**Supervisor:** Dr. Chimah Ezeomah

### Mr. Amarikwa-Obi 

(Visting Masters Student from the University of Malta - Faculty of Education)

**Masters Project Supervisor:** Prof. Chimah Ezeomah 

### Shimfe N. Y. Shimfe

**Thesis Title:** Factors influencing the Retention of Primary School Teachers in Jalingo L.G.A., Gongola State. A research report presented to the Faculty of Education, University of Jos, as a partial fulfillment for the award of the post graduate diploma in education (PGDE). 

**Month/Year:** June 1980. 

**Supervisor:** Mr. Chimah Ezeomah

### M. M. Bawa

**Thesis Title:** The improvement of School Plants: A Challenge to Universal Basic Education

**Year:** 1988 (circa)

### Mr. Vincent Avreson Kigbu

**Undergraduate Student**

### Dr. M. I. Junaid

(Readership Candidate in Education at the Usmanu Danfodiyo University, Sokoto)

**External Assessor:** Prof. Chimah Ezeomah

**Year:** 1994 (circa)

### Yakubu James Awan

**Course:** EASS 570: Methodology of Educational Planning

**Lecturer:** Professor Ardo C. Ezeomah

**Year:** 1997

### Jacob H. Baruda 

**Course:** EASS 570: Methodology of Educational Planning

**Lecturer:** Professor Ardo C. Ezeomah

**Year:** 1997

### Jatau A. Audu 

**Course:** EASS 570: Methodology of Educational Planning

**Lecturer:** Professor Ardo C. Ezeomah

**Year:** 1997

### Mrs. S. A. Galadima 

**Course:** EASS 570: Methodology of Educational Planning

**Lecturer:** Professor Ardo C. Ezeomah

**Year:** 1997

### Mrs. Zitta Filicia R 

**Course:** EASS 570: Methodology of Educational Planning

**Lecturer:** Professor Ardo C. Ezeomah

**Year:** 1997

### Halliru A. Sadiq 

**Course:** EASS 570: Methodology of Educational Planning

**Lecturer:** Professor Ardo C. Ezeomah

**Year:** 1997

### Gayus B. Diana 

**Course:** EASS 570: Methodology of Educational Planning

**Lecturer:** Professor Ardo C. Ezeomah

**Year:** 1997

### Ohale Ijeoma E. 

**Course:** EASS 570: Methodology of Educational Planning

**Lecturer:** Professor Ardo C. Ezeomah

**Year:** 1997

### Rishante P.S. 

**Course:** EASS 570: Methodology of Educational Planning

**Lecturer:** Professor Ardo C. Ezeomah

**Year:** 1997

### Mrs. Jiddere Musa Kaibo 

**Course:** EASS 570: Methodology of Educational Planning

**Lecturer:** Professor Ardo C. Ezeomah

**Year:** 1998

### Mrs. Martina I. Nse

**Course:** EASS 653

**Lecturer:** Professor Ardo C. Ezeomah

**Year:** 